version: '3.8'

services:
  main:
    container_name: main
    build:
      context: .
      dockerfile: Dockerfile.development
    env_file:
      - .development.env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 5000:5000
      - 9229:9229
    command: npm run start:dev
    depends_on:
      - postgres
    restart: always

  postgres:
    container_name: postgres
    image: postgres:12
    env_file:
      - .development.env
    environment:
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata-dev:/var/lib/postgresql/data
    restart: always
  
  redis:
    image: redis:alpine3.14
    container_name: redis
    ports:
      - '6379-6379'

volumes:
  pgdata-dev: